//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ERPModel", "FK_CONTRATOS_CLIENTES1", "CLIENTES", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SISGRES.CLIENTES), "CONTRATOS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SISGRES.CONTRATOS), true)]
[assembly: EdmRelationshipAttribute("ERPModel", "FK_PARTIDAS_CONTRATOS", "CONTRATOS", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SISGRES.CONTRATOS), "PARTIDAS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SISGRES.PARTIDAS), true)]

#endregion

namespace SISGRES
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ERP : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ERP object using the connection string found in the 'ERP' section of the application configuration file.
        /// </summary>
        public ERP() : base("name=ERP", "ERP")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ERP object.
        /// </summary>
        public ERP(string connectionString) : base(connectionString, "ERP")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ERP object.
        /// </summary>
        public ERP(EntityConnection connection) : base(connection, "ERP")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CLIENTES> CLIENTES
        {
            get
            {
                if ((_CLIENTES == null))
                {
                    _CLIENTES = base.CreateObjectSet<CLIENTES>("CLIENTES");
                }
                return _CLIENTES;
            }
        }
        private ObjectSet<CLIENTES> _CLIENTES;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CONTRATOS> CONTRATOS
        {
            get
            {
                if ((_CONTRATOS == null))
                {
                    _CONTRATOS = base.CreateObjectSet<CONTRATOS>("CONTRATOS");
                }
                return _CONTRATOS;
            }
        }
        private ObjectSet<CONTRATOS> _CONTRATOS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MENU> MENU
        {
            get
            {
                if ((_MENU == null))
                {
                    _MENU = base.CreateObjectSet<MENU>("MENU");
                }
                return _MENU;
            }
        }
        private ObjectSet<MENU> _MENU;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PARTIDAS> PARTIDAS
        {
            get
            {
                if ((_PARTIDAS == null))
                {
                    _PARTIDAS = base.CreateObjectSet<PARTIDAS>("PARTIDAS");
                }
                return _PARTIDAS;
            }
        }
        private ObjectSet<PARTIDAS> _PARTIDAS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CLIENTES EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCLIENTES(CLIENTES cLIENTES)
        {
            base.AddObject("CLIENTES", cLIENTES);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CONTRATOS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCONTRATOS(CONTRATOS cONTRATOS)
        {
            base.AddObject("CONTRATOS", cONTRATOS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MENU EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMENU(MENU mENU)
        {
            base.AddObject("MENU", mENU);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PARTIDAS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPARTIDAS(PARTIDAS pARTIDAS)
        {
            base.AddObject("PARTIDAS", pARTIDAS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ERPModel", Name="CLIENTES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CLIENTES : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CLIENTES object.
        /// </summary>
        /// <param name="iD_CLIENTE">Initial value of the ID_CLIENTE property.</param>
        public static CLIENTES CreateCLIENTES(global::System.Int32 iD_CLIENTE)
        {
            CLIENTES cLIENTES = new CLIENTES();
            cLIENTES.ID_CLIENTE = iD_CLIENTE;
            return cLIENTES;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NUMERO
        {
            get
            {
                return _NUMERO;
            }
            set
            {
                OnNUMEROChanging(value);
                ReportPropertyChanging("NUMERO");
                _NUMERO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NUMERO");
                OnNUMEROChanged();
            }
        }
        private Nullable<global::System.Int32> _NUMERO;
        partial void OnNUMEROChanging(Nullable<global::System.Int32> value);
        partial void OnNUMEROChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NOMBRE
        {
            get
            {
                return _NOMBRE;
            }
            set
            {
                OnNOMBREChanging(value);
                ReportPropertyChanging("NOMBRE");
                _NOMBRE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NOMBRE");
                OnNOMBREChanged();
            }
        }
        private global::System.String _NOMBRE;
        partial void OnNOMBREChanging(global::System.String value);
        partial void OnNOMBREChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DIRECCION
        {
            get
            {
                return _DIRECCION;
            }
            set
            {
                OnDIRECCIONChanging(value);
                ReportPropertyChanging("DIRECCION");
                _DIRECCION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DIRECCION");
                OnDIRECCIONChanged();
            }
        }
        private global::System.String _DIRECCION;
        partial void OnDIRECCIONChanging(global::System.String value);
        partial void OnDIRECCIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TELEFONO
        {
            get
            {
                return _TELEFONO;
            }
            set
            {
                OnTELEFONOChanging(value);
                ReportPropertyChanging("TELEFONO");
                _TELEFONO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TELEFONO");
                OnTELEFONOChanged();
            }
        }
        private global::System.String _TELEFONO;
        partial void OnTELEFONOChanging(global::System.String value);
        partial void OnTELEFONOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RFC
        {
            get
            {
                return _RFC;
            }
            set
            {
                OnRFCChanging(value);
                ReportPropertyChanging("RFC");
                _RFC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RFC");
                OnRFCChanged();
            }
        }
        private global::System.String _RFC;
        partial void OnRFCChanging(global::System.String value);
        partial void OnRFCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_CLIENTE
        {
            get
            {
                return _ID_CLIENTE;
            }
            set
            {
                if (_ID_CLIENTE != value)
                {
                    OnID_CLIENTEChanging(value);
                    ReportPropertyChanging("ID_CLIENTE");
                    _ID_CLIENTE = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_CLIENTE");
                    OnID_CLIENTEChanged();
                }
            }
        }
        private global::System.Int32 _ID_CLIENTE;
        partial void OnID_CLIENTEChanging(global::System.Int32 value);
        partial void OnID_CLIENTEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CORREO
        {
            get
            {
                return _CORREO;
            }
            set
            {
                OnCORREOChanging(value);
                ReportPropertyChanging("CORREO");
                _CORREO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CORREO");
                OnCORREOChanged();
            }
        }
        private global::System.String _CORREO;
        partial void OnCORREOChanging(global::System.String value);
        partial void OnCORREOChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ERPModel", "FK_CONTRATOS_CLIENTES1", "CONTRATOS")]
        public EntityCollection<CONTRATOS> CONTRATOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CONTRATOS>("ERPModel.FK_CONTRATOS_CLIENTES1", "CONTRATOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CONTRATOS>("ERPModel.FK_CONTRATOS_CLIENTES1", "CONTRATOS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ERPModel", Name="CONTRATOS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CONTRATOS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CONTRATOS object.
        /// </summary>
        /// <param name="iD_CONTRATO">Initial value of the ID_CONTRATO property.</param>
        public static CONTRATOS CreateCONTRATOS(global::System.Int32 iD_CONTRATO)
        {
            CONTRATOS cONTRATOS = new CONTRATOS();
            cONTRATOS.ID_CONTRATO = iD_CONTRATO;
            return cONTRATOS;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_CONTRATO
        {
            get
            {
                return _ID_CONTRATO;
            }
            set
            {
                if (_ID_CONTRATO != value)
                {
                    OnID_CONTRATOChanging(value);
                    ReportPropertyChanging("ID_CONTRATO");
                    _ID_CONTRATO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_CONTRATO");
                    OnID_CONTRATOChanged();
                }
            }
        }
        private global::System.Int32 _ID_CONTRATO;
        partial void OnID_CONTRATOChanging(global::System.Int32 value);
        partial void OnID_CONTRATOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_CLIENTE
        {
            get
            {
                return _ID_CLIENTE;
            }
            set
            {
                OnID_CLIENTEChanging(value);
                ReportPropertyChanging("ID_CLIENTE");
                _ID_CLIENTE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_CLIENTE");
                OnID_CLIENTEChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_CLIENTE;
        partial void OnID_CLIENTEChanging(Nullable<global::System.Int32> value);
        partial void OnID_CLIENTEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NUMERO
        {
            get
            {
                return _NUMERO;
            }
            set
            {
                OnNUMEROChanging(value);
                ReportPropertyChanging("NUMERO");
                _NUMERO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NUMERO");
                OnNUMEROChanged();
            }
        }
        private global::System.String _NUMERO;
        partial void OnNUMEROChanging(global::System.String value);
        partial void OnNUMEROChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRIPCION
        {
            get
            {
                return _DESCRIPCION;
            }
            set
            {
                OnDESCRIPCIONChanging(value);
                ReportPropertyChanging("DESCRIPCION");
                _DESCRIPCION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRIPCION");
                OnDESCRIPCIONChanged();
            }
        }
        private global::System.String _DESCRIPCION;
        partial void OnDESCRIPCIONChanging(global::System.String value);
        partial void OnDESCRIPCIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MONTO_USD
        {
            get
            {
                return _MONTO_USD;
            }
            set
            {
                OnMONTO_USDChanging(value);
                ReportPropertyChanging("MONTO_USD");
                _MONTO_USD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MONTO_USD");
                OnMONTO_USDChanged();
            }
        }
        private Nullable<global::System.Decimal> _MONTO_USD;
        partial void OnMONTO_USDChanging(Nullable<global::System.Decimal> value);
        partial void OnMONTO_USDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MONTO_MXN
        {
            get
            {
                return _MONTO_MXN;
            }
            set
            {
                OnMONTO_MXNChanging(value);
                ReportPropertyChanging("MONTO_MXN");
                _MONTO_MXN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MONTO_MXN");
                OnMONTO_MXNChanged();
            }
        }
        private Nullable<global::System.Decimal> _MONTO_MXN;
        partial void OnMONTO_MXNChanging(Nullable<global::System.Decimal> value);
        partial void OnMONTO_MXNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> INICIO
        {
            get
            {
                return _INICIO;
            }
            set
            {
                OnINICIOChanging(value);
                ReportPropertyChanging("INICIO");
                _INICIO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("INICIO");
                OnINICIOChanged();
            }
        }
        private Nullable<global::System.DateTime> _INICIO;
        partial void OnINICIOChanging(Nullable<global::System.DateTime> value);
        partial void OnINICIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TERMINO
        {
            get
            {
                return _TERMINO;
            }
            set
            {
                OnTERMINOChanging(value);
                ReportPropertyChanging("TERMINO");
                _TERMINO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TERMINO");
                OnTERMINOChanged();
            }
        }
        private Nullable<global::System.DateTime> _TERMINO;
        partial void OnTERMINOChanging(Nullable<global::System.DateTime> value);
        partial void OnTERMINOChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ERPModel", "FK_CONTRATOS_CLIENTES1", "CLIENTES")]
        public CLIENTES CLIENTES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENTES>("ERPModel.FK_CONTRATOS_CLIENTES1", "CLIENTES").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENTES>("ERPModel.FK_CONTRATOS_CLIENTES1", "CLIENTES").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CLIENTES> CLIENTESReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENTES>("ERPModel.FK_CONTRATOS_CLIENTES1", "CLIENTES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CLIENTES>("ERPModel.FK_CONTRATOS_CLIENTES1", "CLIENTES", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ERPModel", "FK_PARTIDAS_CONTRATOS", "PARTIDAS")]
        public EntityCollection<PARTIDAS> PARTIDAS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PARTIDAS>("ERPModel.FK_PARTIDAS_CONTRATOS", "PARTIDAS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PARTIDAS>("ERPModel.FK_PARTIDAS_CONTRATOS", "PARTIDAS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ERPModel", Name="MENU")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MENU : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MENU object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static MENU CreateMENU(global::System.Int32 id)
        {
            MENU mENU = new MENU();
            mENU.Id = id;
            return mENU;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ParentId;
        partial void OnParentIdChanging(Nullable<global::System.Int32> value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ToolTip
        {
            get
            {
                return _ToolTip;
            }
            set
            {
                OnToolTipChanging(value);
                ReportPropertyChanging("ToolTip");
                _ToolTip = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ToolTip");
                OnToolTipChanged();
            }
        }
        private global::System.String _ToolTip;
        partial void OnToolTipChanging(global::System.String value);
        partial void OnToolTipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NavigateUrl
        {
            get
            {
                return _NavigateUrl;
            }
            set
            {
                OnNavigateUrlChanging(value);
                ReportPropertyChanging("NavigateUrl");
                _NavigateUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NavigateUrl");
                OnNavigateUrlChanged();
            }
        }
        private global::System.String _NavigateUrl;
        partial void OnNavigateUrlChanging(global::System.String value);
        partial void OnNavigateUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageUrlField
        {
            get
            {
                return _ImageUrlField;
            }
            set
            {
                OnImageUrlFieldChanging(value);
                ReportPropertyChanging("ImageUrlField");
                _ImageUrlField = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageUrlField");
                OnImageUrlFieldChanged();
            }
        }
        private global::System.String _ImageUrlField;
        partial void OnImageUrlFieldChanging(global::System.String value);
        partial void OnImageUrlFieldChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ERPModel", Name="PARTIDAS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PARTIDAS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PARTIDAS object.
        /// </summary>
        /// <param name="iD_PARTIDA">Initial value of the ID_PARTIDA property.</param>
        public static PARTIDAS CreatePARTIDAS(global::System.Int32 iD_PARTIDA)
        {
            PARTIDAS pARTIDAS = new PARTIDAS();
            pARTIDAS.ID_PARTIDA = iD_PARTIDA;
            return pARTIDAS;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_PARTIDA
        {
            get
            {
                return _ID_PARTIDA;
            }
            set
            {
                if (_ID_PARTIDA != value)
                {
                    OnID_PARTIDAChanging(value);
                    ReportPropertyChanging("ID_PARTIDA");
                    _ID_PARTIDA = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_PARTIDA");
                    OnID_PARTIDAChanged();
                }
            }
        }
        private global::System.Int32 _ID_PARTIDA;
        partial void OnID_PARTIDAChanging(global::System.Int32 value);
        partial void OnID_PARTIDAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_CONTRATO
        {
            get
            {
                return _ID_CONTRATO;
            }
            set
            {
                OnID_CONTRATOChanging(value);
                ReportPropertyChanging("ID_CONTRATO");
                _ID_CONTRATO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_CONTRATO");
                OnID_CONTRATOChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_CONTRATO;
        partial void OnID_CONTRATOChanging(Nullable<global::System.Int32> value);
        partial void OnID_CONTRATOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NUMERO
        {
            get
            {
                return _NUMERO;
            }
            set
            {
                OnNUMEROChanging(value);
                ReportPropertyChanging("NUMERO");
                _NUMERO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NUMERO");
                OnNUMEROChanged();
            }
        }
        private global::System.String _NUMERO;
        partial void OnNUMEROChanging(global::System.String value);
        partial void OnNUMEROChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRIPCION
        {
            get
            {
                return _DESCRIPCION;
            }
            set
            {
                OnDESCRIPCIONChanging(value);
                ReportPropertyChanging("DESCRIPCION");
                _DESCRIPCION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRIPCION");
                OnDESCRIPCIONChanged();
            }
        }
        private global::System.String _DESCRIPCION;
        partial void OnDESCRIPCIONChanging(global::System.String value);
        partial void OnDESCRIPCIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MONTO_USD
        {
            get
            {
                return _MONTO_USD;
            }
            set
            {
                OnMONTO_USDChanging(value);
                ReportPropertyChanging("MONTO_USD");
                _MONTO_USD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MONTO_USD");
                OnMONTO_USDChanged();
            }
        }
        private Nullable<global::System.Decimal> _MONTO_USD;
        partial void OnMONTO_USDChanging(Nullable<global::System.Decimal> value);
        partial void OnMONTO_USDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MONTO_MXN
        {
            get
            {
                return _MONTO_MXN;
            }
            set
            {
                OnMONTO_MXNChanging(value);
                ReportPropertyChanging("MONTO_MXN");
                _MONTO_MXN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MONTO_MXN");
                OnMONTO_MXNChanged();
            }
        }
        private Nullable<global::System.Decimal> _MONTO_MXN;
        partial void OnMONTO_MXNChanging(Nullable<global::System.Decimal> value);
        partial void OnMONTO_MXNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_UNIDAD_MEDIDA
        {
            get
            {
                return _ID_UNIDAD_MEDIDA;
            }
            set
            {
                OnID_UNIDAD_MEDIDAChanging(value);
                ReportPropertyChanging("ID_UNIDAD_MEDIDA");
                _ID_UNIDAD_MEDIDA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_UNIDAD_MEDIDA");
                OnID_UNIDAD_MEDIDAChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_UNIDAD_MEDIDA;
        partial void OnID_UNIDAD_MEDIDAChanging(Nullable<global::System.Int32> value);
        partial void OnID_UNIDAD_MEDIDAChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ERPModel", "FK_PARTIDAS_CONTRATOS", "CONTRATOS")]
        public CONTRATOS CONTRATOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CONTRATOS>("ERPModel.FK_PARTIDAS_CONTRATOS", "CONTRATOS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CONTRATOS>("ERPModel.FK_PARTIDAS_CONTRATOS", "CONTRATOS").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CONTRATOS> CONTRATOSReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CONTRATOS>("ERPModel.FK_PARTIDAS_CONTRATOS", "CONTRATOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CONTRATOS>("ERPModel.FK_PARTIDAS_CONTRATOS", "CONTRATOS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ERPModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }

    #endregion

    
}
